name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Версия релиза (например: 123)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Docker image exists
        env:
          YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
        run: |
          # Проверка существования образа в Container Registry
          echo ${{ secrets.YC_IAM_TOKEN }} | docker login \
            --username iam \
            --password-stdin \
            cr.yandex

          # Проверка наличия образа с тегом версии
          docker pull cr.yandex/$YC_REGISTRY_ID/app:$RELEASE_VERSION || exit 1
          # Проверка наличия образа с тегом latest
          docker pull cr.yandex/$YC_REGISTRY_ID/app:${RELEASE_VERSION}_latest || exit 1
          
          echo "✅ Оба образа существуют в Container Registry"

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Остановка и удаление предыдущего контейнера
            docker stop app || true
            docker rm app || true
            
            # Обновление образа и запуск нового контейнера
            echo ${{ secrets.YC_IAM_TOKEN }} | docker login \
              --username iam \
              --password-stdin \
              cr.yandex
            
            docker pull cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
            docker run -d \
              --name app \
              -p 3000:3000 \
              cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
            
            echo "🚀 Приложение успешно запущено!"

      - name: Find release issue
        id: find_issue
        uses: actions/github-script@v7
        env:
          VERSION: ${{ github.event.inputs.release_version }}
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            
            const targetIssue = issues.find(issue => issue.title.includes(`Release v${process.env.VERSION}`));                     
            
            if (!targetIssue) {
              core.setFailed(`Release issue for version ${process.env.RELEASE_VERSION} not found`);
              return 0;
            }
            
            return targetIssue.number;

      - name: Add deployment comment to issue
        uses: actions/github-script@v7
        if: steps.find_issue.outputs.result != '0'
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.find_issue.outputs.result }},
              body: `🚀 **Выкатка в прод завершена!**\n` +
                    `- Дата: ${new Date().toISOString().split('T')[0]}\n` +
                    `- Ответственный: @${{ github.actor }}\n` +
                    `- Версия: ${{ github.event.inputs.release_version }}\n` +
                    `- Образ: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest`
            });